[package]
name = "bench-transformer"
version = "0.1.0"
edition = "2021"
publish = false

[[bench]]
name = "transformer"
harness = false

[[bin]]
name = "oxc"
path = "src/oxc.rs"
test    = false
doctest = false

[[bin]]
name = "swc"
path = "src/swc.rs"
test    = false
doctest = false

[dependencies]
oxc = { version = "0.14.0", features = ["transformer", "codegen"] }

swc = "0.278.0"
swc_common = "0.34.0"
swc_ecma_ast = "0.115.0"
swc_ecma_parser = { version = "0.146.0", features = ["typescript"] }
swc_ecma_transforms = "0.232.0"
swc_ecma_transforms_react = "0.186.0"
swc_ecma_transforms_typescript = "0.191.0"
swc_ecma_visit = "0.101.0"

num_cpus = "1.16.0"
criterion2  = { version = "0.10.0", default-features = false }
rayon = "1.10.0"
mimalloc = "0.1.42"

[features]
codspeed = ["criterion2/codspeed"]

[profile.release]
opt-level     = 3
lto           = "fat"
codegen-units = 1
strip         = "symbols"
debug         = false
panic         = "abort"

